version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - DB_URL=mongodb://host.docker.internal:27019/dbchat
  mongo:
    image: mongo:latest
    ports:
      - "27019:27017"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d/
    ports:
      - "5143:5432"
